### ISSUE TITLE
Unable to run multiple functions

### ISSUE THREAD

**Issue by kstrandli** [sisoe24/NukeServerSocket#21]
Hi!

Whenever I try to run a function inside another function, I get an error and connection closes.
This simple test code will fail to execute:

```
def dummyFuncA():
    print("A")

def dummyFuncB():
    print("B")
    dummyFuncA()

dummyFuncB()

```

Result:
[2022-11-21T00:30:40.497Z] - Try connecting to 192.168.0.23:54321
[2022-11-21T00:30:40.497Z] - Connected.
[2022-11-21T00:30:40.497Z] - Message ready.
[2022-11-21T00:30:50.500Z] - Connection timeout.
[2022-11-21T00:30:50.501Z] - Connection closed. Had Errors: true

I figured it was some scope issue, so I can work around this by throwing everything into a class for now.

```
class NukeTool():
    def init(self):
        pass

    def runMyStuff(self):
        self.dummyFuncA()
        self.dummyFuncB()

    def dummyFuncA(self):
        print("A")

    def dummyFuncB(self):
        print("B")

myClass = NukeTool()
myClass.runMyStuff()

```

Any solutions or obvious alternatives I'm missing?

Thanks!

**Comment by sisoe24** [comment]
I've transferred the issue, and I will close it.
