### ISSUE TITLE
NukeServerSocket not appearing in Nuke menu

### ISSUE THREAD

**Issue by Azool2** [sisoe24/NukeServerSocket#27]
Description:

I installed NukeServerSocket, but when I click on it in Nuke, it does not appear. I am using Nuke Indie, and I wonder if this could be the cause of the problem. In my menu.py file, I have only written "import NukeServerSocket". Is this sufficient?

Steps to reproduce:

Install NukeServerSocket in .nuke.
Open Nuke Indie.
Click on the NukeServerSocket option in the menu.
Expected behavior:

The NukeServerSocket option should appear. 

Actual behavior:

The NukeServerSocket option appear empty.

Environment:

Operating system: Windows 11 
Nuke version: 14.03

the Foldername in .nuke: NukeServerSocket

here the menu.py : https://github.com/Azool2/menu.py

Thank you very much.

**Comment by sisoe24** [comment]
Hello! Thank you for getting in touch.

The issue you're experiencing may be due to a limitation of Nuke Indie. Both Nuke Non-Commercial and Nuke Indie have restrictions on Python usage, allowing only ten commands, which can be quite limiting. However, I may be able to confirm this if I obtain a trial license for Nuke Indie.

Let's see if we can troubleshoot the issue together. Have you been able to check the terminal to see if there are any unexpected messages? Windows typically opens the console by default, but you could launch the Nuke executable directly from your console/terminal to view all Nuke launch information.

Also, could you let me know how you installed NukeServerSocket?

**Comment by Azool2** [comment]
I just record a video to show the problem better. 

https://www.youtube.com/watch?v=XygkxNQf2rE&ab_channel=MrKenedi

and here the promt form nuke script: 

import nukescripts.ViewerProcess;nukescripts.ViewerProcess.unregister_viewers("E:/ProgramFiles/Nuke14.03/plugins/OCIOConfigs/configs/nuke-default/config.ocio");
import nukescripts.ViewerProcess; nukescripts.ViewerProcess._register_viewer_processes(defaultLUTS = True, ocioConfigName = "E:/ProgramFiles/Nuke14.03/plugins/OCIOConfigs/configs/nuke-default/config.ocio", also_remove = "default", isReload = False);
import nukescripts.ViewerProcess;nukescripts.ViewerProcess.unregister_viewers("E:/ProgramFiles/Nuke14.03/plugins/OCIOConfigs/configs/nuke-default/config.ocio");
import nukescripts.ViewerProcess; nukescripts.ViewerProcess._register_viewer_processes(defaultLUTS = False, ocioConfigName = "E:/ProgramFiles/Nuke14.03/plugins/OCIOConfigs/configs/nuke-default/config.ocio", also_remove = "default", isReload = False);
import nukescripts.ViewerProcess;nukescripts.ViewerProcess.unregister_viewers("E:/ProgramFiles/Nuke14.03/plugins/OCIOConfigs/configs/nuke-default/config.ocio");
import nukescripts.ViewerProcess; nukescripts.ViewerProcess._register_viewer_processes(defaultLUTS = False, ocioConfigName = "E:/ProgramFiles/Nuke14.03/plugins/OCIOConfigs/configs/nuke-default/config.ocio", also_remove = "default", isReload = False);
nuke.createNode("Viewer", inpanel=False)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'NukeServerSocket' has no attribute 'nukeserversocket'

Thank you for your time.

**Comment by sisoe24** [comment]
Based on what I see, it seems that you are moving the contents of the NukeServerSocket folder into the .nuke folder. However, the correct approach would be to move the entire NukeServerSocket folder inside the .nuke folder.

![image](https://user-images.githubusercontent.com/28490646/233456171-b3aec5e5-7898-4e01-841a-ca90d9c00d03.png)

I recommend deleting all the files and folders you have moved so far and instead using the [NukeTools](https://marketplace.visualstudio.com/items?itemName=virgilsisoe.nuke-tools) extension in Visual Studio Code. By calling the command `Nuke: Add NukeServerSocket` the installation process will be handled for you automatically.


![ezgif com-gif-maker](https://user-images.githubusercontent.com/28490646/233457366-9062376c-c635-4fd8-abcf-abc4266db851.gif)

**Comment by Azool2** [comment]
That was exactly the problem. It show up in Nuke.  Thank you. But it does not go to work with VS code bcz of Indie limitation. 
Thank you again for your time.

**Comment by sisoe24** [comment]
No problem. 

Even if you have the Nuke Indie limit, you can still use Nuke Tools with the Python stubs since they don't require Nuke to function.

Feel free to reach out to me anytime if you have any further questions.
